id: 08cca443-0855-42c6-adfd-064bdbd6a178
name: guest-agent-test
description: 'Test guest agent - create VM, start (validates agent via IP fetch), cleanup'
jobs:
  - name: guest-agent
    description: 'Create VM, start (validates guest agent by fetching IP), cleanup'
    steps:
      - name: auth
        description: Authenticate with Proxmox
        task:
          type: model_method
          modelIdOrName: keebDev02
          methodName: auth
        dependsOn: []
        weight: 0
      - name: create-vm
        description: 'Create a test VM with agent:1 and PXE boot (no disk)'
        task:
          type: model_method
          modelIdOrName: fleet
          methodName: create
          inputs:
            vmName: test-guest-agent-vm
            memory: 1024
            cores: 1
            sockets: 1
            diskSize: 0
        dependsOn:
          - step: auth
            condition:
              type: succeeded
        weight: 0
      - name: start-vm
        description: Start the VM and wait for guest agent IP
        task:
          type: model_method
          modelIdOrName: fleet
          methodName: start
          inputs:
            vmName: test-guest-agent-vm
        dependsOn:
          - step: create-vm
            condition:
              type: succeeded
        weight: 0
      - name: stop-vm
        description: Stop the test VM
        task:
          type: model_method
          modelIdOrName: fleet
          methodName: stop
          inputs:
            vmName: test-guest-agent-vm
        dependsOn:
          - step: start-vm
            condition:
              type: succeeded
        weight: 0
      - name: delete-vm
        description: Delete the test VM
        task:
          type: model_method
          modelIdOrName: fleet
          methodName: delete
          inputs:
            vmName: test-guest-agent-vm
        dependsOn:
          - step: stop-vm
            condition:
              type: succeeded
        weight: 0
    dependsOn: []
    weight: 0
version: 1
