id: a2408304-0d10-4cf9-8f6e-404856cee733
name: setup-docker
description: Install Docker Engine on a running VM by name
inputs:
  vmName:
    type: string
    required: true
    description: Name of the VM to install Docker on
jobs:
  - name: setup
    description: Auth, lookup VM via fleet, install Docker
    steps:
      - name: auth
        description: Authenticate with Proxmox via keebDev02
        task:
          type: model_method
          modelIdOrName: keebDev02
          methodName: auth
        dependsOn: []
        weight: 0
      - name: lookup
        description: Look up VM to get IP
        task:
          type: model_method
          modelIdOrName: fleet
          methodName: lookup
          inputs:
            vmName: '${{ inputs.vmName }}'
        dependsOn:
          - step: auth
            condition:
              type: succeeded
        weight: 0
      - name: install-docker
        description: Install Docker via SSH
        task:
          type: model_method
          modelIdOrName: dockerEngine
          methodName: install
          inputs:
            vmName: '${{ inputs.vmName }}'
        dependsOn:
          - step: lookup
            condition:
              type: succeeded
        weight: 0
    dependsOn: []
    weight: 0
version: 1
