id: 8d6c048b-2a6e-4526-911c-0237006205d2
name: start-vm
description: 'Start a VM by name (idempotent, waits for IP)'
inputs:
  vmName:
    type: string
    required: true
    description: Name of the VM to start
jobs:
  - name: start
    steps:
      - name: auth
        task:
          type: model_method
          modelIdOrName: keebDev02
          methodName: auth
        dependsOn: []
        weight: 0
      - name: start-vm
        task:
          type: model_method
          modelIdOrName: fleet
          methodName: start
          inputs:
            vmName: '${{ inputs.vmName }}'
        dependsOn:
          - step: auth
            condition:
              type: succeeded
        weight: 0
    dependsOn: []
    weight: 0
version: 1
