id: fa5db4d6-7a25-418a-b647-d469fb1bf68d
name: setup-tailscale
description: Install Tailscale and authenticate on a running VM by name
inputs:
  vmName:
    type: string
    required: true
    description: Name of the VM to install Tailscale on
jobs:
  - name: setup
    description: Auth, lookup VM via fleet, install Tailscale
    steps:
      - name: auth
        description: Authenticate with Proxmox via keebDev02
        task:
          type: model_method
          modelIdOrName: keebDev02
          methodName: auth
        dependsOn: []
        weight: 0
      - name: lookup
        description: Look up VM to get IP
        task:
          type: model_method
          modelIdOrName: fleet
          methodName: lookup
          inputs:
            vmName: '${{ inputs.vmName }}'
        dependsOn:
          - step: auth
            condition:
              type: succeeded
        weight: 0
      - name: install-tailscale
        description: Install Tailscale and authenticate
        task:
          type: model_method
          modelIdOrName: tailscaleNode
          methodName: install
          inputs:
            vmName: '${{ inputs.vmName }}'
        dependsOn:
          - step: lookup
            condition:
              type: succeeded
        weight: 0
    dependsOn: []
    weight: 0
version: 1
