id: 7411c28f-1e1e-40cc-9088-f9d73b135261
name: start-allthemons
description: Start the allthemons Minecraft server
jobs:
  - name: main
    description: Auth, start allthemons VM via fleet, then start Minecraft server
    steps:
      - name: auth
        description: Authenticate with Proxmox via keebDev02
        task:
          type: model_method
          modelIdOrName: keebDev02
          methodName: auth
        dependsOn: []
        weight: 0
      - name: ensure-vm-running
        description: Start allthemons VM if stopped and wait for IP
        task:
          type: model_method
          modelIdOrName: fleet
          methodName: start
          inputs:
            vmName: allthemons
        dependsOn:
          - step: auth
            condition:
              type: succeeded
        weight: 0
      - name: start-minecraft
        description: Start Minecraft server and wait for ready
        task:
          type: model_method
          modelIdOrName: allthemonsMinecraft
          methodName: startMinecraftServer
        dependsOn:
          - step: ensure-vm-running
            condition:
              type: succeeded
        weight: 0
    dependsOn: []
    weight: 0
version: 1
