id: bf99525b-2266-44b3-8e8b-43c70a1e4a9d
name: configure-proxy
description: Configure nginx stream proxy on treehouse for a backend service
inputs:
  vmName:
    type: string
    required: true
    description: Service name (e.g. 'allthemons')
  targetIp:
    type: string
    required: true
    description: Tailscale IP of the backend service
  portMap:
    type: string
    required: true
    description: "Port mappings: 'listen:backend[/proto],...' e.g. '25565:25565,7777:7777/udp'"
jobs:
  - name: configure
    description: Write nginx config and update docker-compose ports
    steps:
      - name: configure-proxy
        description: Configure stream proxy for the service
        task:
          type: model_method
          modelIdOrName: treehouse
          methodName: configure
          inputs:
            vmName: '${{ inputs.vmName }}'
            targetIp: '${{ inputs.targetIp }}'
            portMap: '${{ inputs.portMap }}'
        dependsOn: []
        weight: 0
    dependsOn: []
    weight: 0
version: 1
