id: 31e53f62-ad3f-4851-a2e6-bd320f8bfe2b
name: start-calamity
description: Start the calamity Terraria server
jobs:
  - name: main
    description: Auth, start calamity VM via fleet, then start Docker Compose services
    steps:
      - name: auth
        description: Authenticate with Proxmox via keebDev02
        task:
          type: model_method
          modelIdOrName: keebDev02
          methodName: auth
        dependsOn: []
        weight: 0
      - name: ensure-vm-running
        description: Start calamity VM if stopped and wait for IP
        task:
          type: model_method
          modelIdOrName: fleet
          methodName: start
          inputs:
            vmName: calamity
        dependsOn:
          - step: auth
            condition:
              type: succeeded
        weight: 0
      - name: start-terraria
        description: Start Docker Compose services
        task:
          type: model_method
          modelIdOrName: calamity
          methodName: start
        dependsOn:
          - step: ensure-vm-running
            condition:
              type: succeeded
        weight: 0
      - name: annotate
        description: Create Grafana annotation
        task:
          type: model_method
          modelIdOrName: grafanaHub
          methodName: createAnnotation
          inputs:
            tags: '["game", "start", "calamity"]'
            text: 'calamity started'
        dependsOn:
          - step: start-terraria
            condition:
              type: succeeded
        weight: 0
    dependsOn: []
    weight: 0
version: 1
